#!/bin/bash
# Setup script for ai-demo-shop repository

TOKEN="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"
OWNER="OhoBEiD"
REPO="ai-demo-shop"
BRANCH="main"

create_file() {
    local path=$1
    local content=$2
    local message=$3
    
    local encoded=$(echo -n "$content" | base64)
    
    curl -s -X PUT \
        -H "Authorization: Bearer $TOKEN" \
        -H "Accept: application/vnd.github+json" \
        "https://api.github.com/repos/$OWNER/$REPO/contents/$path" \
        -d "{\"message\":\"$message\",\"content\":\"$encoded\",\"branch\":\"$BRANCH\"}" > /dev/null
    
    echo "Created: $path"
}

echo "Setting up ai-demo-shop repository..."

# package.json
create_file "package.json" '{
  "name": "ai-demo-shop",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}' "Add package.json"

sleep 1

# next.config.js
create_file "next.config.js" "/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig" "Add next.config.js"

sleep 1

# tsconfig.json
create_file "tsconfig.json" '{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{"name": "next"}],
    "paths": {"@/*": ["./src/*"]}
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}' "Add tsconfig.json"

sleep 1

# tailwind.config.js
create_file "tailwind.config.js" "/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: { extend: {} },
  plugins: [],
}" "Add tailwind.config.js"

sleep 1

# postcss.config.js
create_file "postcss.config.js" "module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}" "Add postcss.config.js"

sleep 1

# .gitignore
create_file ".gitignore" "node_modules
.next
.DS_Store
*.local
.env*.local" "Add .gitignore"

sleep 1

# src/app/globals.css
create_file "src/app/globals.css" "@tailwind base;
@tailwind components;
@tailwind utilities;" "Add globals.css"

sleep 1

# src/app/layout.tsx
create_file "src/app/layout.tsx" "import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'AI Demo Shop',
  description: 'Built by AI Editor',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang=\"en\">
      <body className=\"antialiased\">{children}</body>
    </html>
  )
}" "Add layout.tsx"

sleep 1

# src/app/page.tsx
create_file "src/app/page.tsx" "export default function Home() {
  return (
    <div className=\"min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100\">
      <div className=\"text-center p-8\">
        <h1 className=\"text-5xl font-bold text-gray-900 mb-4\">AI Demo Shop</h1>
        <p className=\"text-xl text-gray-600 mb-8\">Ready to be built by AI!</p>
        <div className=\"bg-white rounded-lg p-6 shadow-lg max-w-md mx-auto\">
          <p className=\"text-sm text-gray-500\">
            Ask the AI to create components, pages, and features.
            <br />Everything you see will be generated by AI.
          </p>
        </div>
      </div>
    </div>
  )
}" "Add page.tsx"

echo ""
echo "✅ Repository setup complete!"
echo "   https://github.com/OhoBEiD/ai-demo-shop"
